In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [6]:
x = np.random.randn(8)

In [7]:
y = np.random.randn(8)

In [8]:
x

array([-0.02550618, -2.69930187, -0.95519743, -0.24606007,  0.44098426,
       -0.14175575, -0.45816682,  0.10496593])

In [9]:
y

array([ 0.68345972,  0.18184885,  0.34597885, -1.36707614, -0.63243047,
        0.0948734 ,  0.04003096,  1.49107232])

In [10]:
np.maximum(x, y)

array([ 0.68345972,  0.18184885,  0.34597885, -0.24606007,  0.44098426,
        0.0948734 ,  0.04003096,  1.49107232])

In [11]:
arr = np.random.randn(7)*5

In [12]:
arr

array([-14.667273  ,  -0.4553394 ,  -0.52028828,  -0.46510392,
        -2.04752157,  -6.01546958,   0.61505808])

In [13]:
remainder, whole_part = np.modf(arr)

In [14]:
remainder

array([-0.667273  , -0.4553394 , -0.52028828, -0.46510392, -0.04752157,
       -0.01546958,  0.61505808])

In [15]:
whole_part

array([-14.,  -0.,  -0.,  -0.,  -2.,  -6.,   0.])

In [16]:
arr

array([-14.667273  ,  -0.4553394 ,  -0.52028828,  -0.46510392,
        -2.04752157,  -6.01546958,   0.61505808])

In [17]:
np.sqrt(arr)

/Users/xiaojingguo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,         nan,         nan,         nan,         nan,
               nan,  0.78425639])

In [18]:
np.sqrt(arr, arr)

/Users/xiaojingguo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([        nan,         nan,         nan,         nan,         nan,
               nan,  0.78425639])

In [19]:
arr

array([        nan,         nan,         nan,         nan,         nan,
               nan,  0.78425639])