In [1]:
import numpy as np

In [2]:
points = np.arange(-5, 5, 0.01)

In [3]:
xs, ys = np.meshgrid(points, points)

In [6]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [9]:
z = np.sqrt(xs**2 +ys**2)

In [10]:
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [11]:
import matplotlib.pyplot as plt

In [12]:
plt.imshow(z, cmap=plt.cm.gray); plt.colorbar()

#### expressing conditional logic as array operations

In [13]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [14]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [15]:
cond = np.array([True, False, True, True, False])

In [16]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]

In [19]:
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [20]:
result = np.where(cond, xarr, yarr)

In [21]:
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [22]:
arr = np.random.randn(4, 4)

In [23]:
arr

array([[-1.98548683,  0.49384658,  1.8373502 , -0.99292383],
       [-1.05783875, -0.17485856, -1.61565314,  0.15088154],
       [ 0.22946774, -0.18389261, -0.16579055, -2.34364793],
       [-0.31617764,  0.61001448,  1.54609215, -0.45755167]])

In [24]:
np.where(arr > 0, 2, -2)

array([[-2,  2,  2, -2],
       [-2, -2, -2,  2],
       [ 2, -2, -2, -2],
       [-2,  2,  2, -2]])

In [25]:
np.where(arr > 0, 2, arr)

array([[-1.98548683,  2.        ,  2.        , -0.99292383],
       [-1.05783875, -0.17485856, -1.61565314,  2.        ],
       [ 2.        , -0.18389261, -0.16579055, -2.34364793],
       [-0.31617764,  2.        ,  2.        , -0.45755167]])

#### mathematical and statistical methods

In [26]:
arr = np.random.randn(5, 4)

In [27]:
arr

array([[  2.43611160e+00,   1.65238343e+00,   1.40223635e+00,
          3.34655015e-01],
       [  2.01118022e+00,   7.75595533e-04,  -1.73902343e-01,
         -7.98817823e-01],
       [ -2.08988008e+00,  -1.60486946e-01,   2.66502008e-01,
         -1.41261991e+00],
       [ -1.58389256e+00,   9.56804636e-02,   8.40884033e-01,
          1.94720628e+00],
       [  1.26748974e+00,  -7.35295117e-01,  -1.28405366e+00,
          5.95177640e-01]])

In [28]:
arr.mean()

0.23056669685582382

In [29]:
np.mean(arr)

0.23056669685582382

In [30]:
arr.sum()

4.6113339371164761

In [31]:
arr.mean(axis=1)

array([ 1.4563466 ,  0.25980891, -0.84912123,  0.32496955, -0.03917035])

In [32]:
arr.mean(axis=0)

array([ 0.40820178,  0.17061149,  0.21033328,  0.13312024])

In [33]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [35]:
arr.cumprod() # 累计积

array([0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

In [37]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [39]:
arr.cumsum(axis=1)

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

#### methods for boolean arrays

In [40]:
arr = np.random.randn(100)

In [42]:
(arr > 0).sum() # number of positive values

49

In [43]:
bools = np.array([False, False, True, False])

In [44]:
bools.any()

True

In [45]:
bools.all()

False

#### sorting

In [46]:
arr = np.random.randn(6)

In [47]:
arr

array([ 0.48648413, -0.74392424, -0.96775786,  1.56517973, -2.12598725,
        0.82621078])

In [48]:
arr.sort()

In [49]:
arr

array([-2.12598725, -0.96775786, -0.74392424,  0.48648413,  0.82621078,
        1.56517973])

In [50]:
arr = np.random.randn(5, 3)

In [51]:
arr

array([[-0.21282876, -1.1284264 ,  0.65898209],
       [ 0.07088728, -0.69758399,  0.28488387],
       [ 0.62515943, -1.89006553,  1.12245697],
       [-0.42290733,  0.52703378, -0.30012497],
       [-0.57864105,  0.07701956, -0.73088279]])

In [52]:
arr.sort(1)

In [53]:
arr

array([[-1.1284264 , -0.21282876,  0.65898209],
       [-0.69758399,  0.07088728,  0.28488387],
       [-1.89006553,  0.62515943,  1.12245697],
       [-0.42290733, -0.30012497,  0.52703378],
       [-0.73088279, -0.57864105,  0.07701956]])

In [54]:
large_arr = np.random.randn(100)

In [57]:
large_arr.sort()
large_arr

array([-2.31228367, -2.16030735, -2.06891343, -1.90111684, -1.58329879,
       -1.47849672, -1.44977791, -1.42158396, -1.42000567, -1.32897872,
       -1.30728938, -1.28614519, -1.22520117, -1.21222812, -1.1937324 ,
       -1.16342452, -1.03677168, -0.97509954, -0.94980602, -0.9491508 ,
       -0.92563129, -0.85864835, -0.82778734, -0.82465119, -0.80948562,
       -0.80878243, -0.76630894, -0.74812511, -0.72385426, -0.67019944,
       -0.59879502, -0.53638205, -0.52183595, -0.5014135 , -0.49777036,
       -0.4663403 , -0.45868549, -0.42438532, -0.40732344, -0.40099478,
       -0.3870898 , -0.38249771, -0.36940212, -0.34342898, -0.30702252,
       -0.28409345, -0.26160982, -0.18620849, -0.15864311, -0.1414344 ,
       -0.13950555, -0.13151757, -0.06265408, -0.02531553, -0.01965929,
        0.00452755,  0.03665305,  0.03751142,  0.04530622,  0.08071248,
        0.12023644,  0.13281773,  0.17546712,  0.19122668,  0.22002227,
        0.22923907,  0.23185222,  0.30794687,  0.31516655,  0.31

In [56]:
large_arr[int(0.05 * len(large_arr))] # 5%quantile

-1.4784967153825377

#### unique and other set logic

In [58]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [59]:
np.unique(names)

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')

In [60]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [61]:
np.unique(ints)

array([1, 2, 3, 4])

In [62]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [63]:
values = np.array([6, 0, 3, 2, 5, 6])

In [64]:
np.in1d(values, [2, 3, 6])

array([ True, False,  True,  True, False,  True], dtype=bool)