In [1]:
import numpy as np

In [3]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('some_array', arr)

In [6]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.savez('array_archive.npz', a=arr, b=arr)

In [9]:
arch = np.load('array_archive.npz')

In [10]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.savez_compressed('arrays_compressed.npz', a=arr, b=arr)

In [13]:
arch_com = np.load('arrays_compressed.npz')

In [14]:
arch_com['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])