## 4.5 Linear Algebra

In [1]:
import numpy as np

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [3]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [4]:
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [5]:
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [6]:
x.dot(y)

array([[  28.,   64.],
       [  67.,  181.]])

In [7]:
np.dot(x, y)

array([[  28.,   64.],
       [  67.,  181.]])

In [8]:
np.dot(x, np.ones(3))

array([  6.,  15.])

In [10]:
from numpy.linalg import inv, qr

In [11]:
X = np.random.randn(5, 5)

In [13]:
mat = X.T.dot(X)

In [14]:
inv(mat)

array([[ 0.70285336, -0.39943012, -0.41226547,  0.27605136,  0.39651501],
       [-0.39943012,  0.34767179,  0.36539053, -0.31209092, -0.33439808],
       [-0.41226547,  0.36539053,  0.8923304 , -0.81130284, -0.92265447],
       [ 0.27605136, -0.31209092, -0.81130284,  1.08260125,  0.98395996],
       [ 0.39651501, -0.33439808, -0.92265447,  0.98395996,  1.27637177]])

In [15]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   3.94917092e-16,  -9.08653911e-17,
          4.31252031e-17,   2.22044605e-16],
       [  1.32129262e-16,   1.00000000e+00,   3.01589848e-16,
         -1.66259410e-17,   0.00000000e+00],
       [ -4.40507609e-16,   2.91566453e-16,   1.00000000e+00,
         -2.64083266e-16,  -8.88178420e-16],
       [  9.57986246e-17,  -3.88630286e-17,  -6.26459474e-16,
          1.00000000e+00,   0.00000000e+00],
       [ -4.44089210e-16,   0.00000000e+00,   0.00000000e+00,
         -8.88178420e-16,   1.00000000e+00]])

In [16]:
q, r = qr(mat)

In [17]:
r

array([[ -7.32550973, -12.49376468,   1.65905245,  -3.14297527,
          2.72463739],
       [  0.        ,  -4.56085668,   6.22622118,   1.55755885,
          2.13997233],
       [  0.        ,   0.        ,  -4.61724019,  -0.85353442,
         -3.07753662],
       [  0.        ,   0.        ,   0.        ,  -3.72815455,
          3.29279536],
       [  0.        ,   0.        ,   0.        ,   0.        ,
          0.51864042]])

## 4.6 Pseudorandom Number Generation

In [18]:
samples = np.random.normal(size=(4, 4))

In [19]:
samples

array([[-0.70521283,  1.1182356 ,  0.12839584, -2.51516551],
       [ 2.1415716 , -0.64708271,  1.27849308,  1.04478721],
       [-0.24290444,  1.27422015, -0.18777608, -0.80480953],
       [-1.71961315,  0.56035511,  0.07415582, -1.46187126]])

In [20]:
from random import normalvariate

In [21]:
N = 1000000

In [22]:
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

952 ms ± 6.15 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
%timeit np.random.normal(size=N)

39.4 ms ± 1.39 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [25]:
np.random.seed(1234)

In [26]:
rng = np.random.RandomState(1234)

In [27]:
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])

## 4.7 Example: Random Walks

In [33]:
import random
positio = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [45]:
import matplotlib.pyplot as plt
plt.plot(walk[:100])

In [46]:
nsteps = 1000

In [47]:
draws = np.random.randint(0, 2, size=nsteps)

In [49]:
steps = np.where(draws > 0, 1, -1)

In [50]:
walk = steps.cumsum()

In [51]:
walk.min()

-9

In [52]:
walk.max()

60

In [53]:
(np.abs(walk)>=10).argmax()

297

In [54]:
nwalks = 5000

In [55]:
nsteps = 1000

In [56]:
draws = np.random.randint(0, 2, size=(nwalks, nsteps))

In [57]:
steps = np.where(draws > 0, 1, -1)

In [58]:
walks = steps.cumsum(1)

In [60]:
walks

array([[  1,   2,   3, ...,  46,  47,  46],
       [  1,   0,   1, ...,  40,  41,  42],
       [  1,   2,   3, ..., -26, -27, -28],
       ..., 
       [  1,   0,   1, ...,  64,  65,  66],
       [  1,   2,   1, ...,   2,   1,   0],
       [ -1,  -2,  -3, ...,  32,  33,  34]])

In [61]:
hits30 = (np.abs(walks) >= 30).any(1)

In [62]:
hits30

array([ True,  True,  True, ...,  True, False,  True], dtype=bool)

In [63]:
hits30.sum()

3368

In [64]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)

In [65]:
crossing_times.mean()

509.99762470308787

In [66]:
crossing_times

array([133, 395, 343, ..., 409, 297, 747])