In [1]:
import numpy as np

In [2]:
arr = np.arange(15).reshape((3, 5))

In [3]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [5]:
arr = np.random.randn(6, 3)

In [6]:
arr

array([[ 0.26920339, -1.44863973,  1.56675295],
       [ 0.12641296,  0.80119011, -0.96552235],
       [-1.58854741,  0.79510601, -0.63451728],
       [-0.46644127,  0.54081104,  1.57357139],
       [-1.83445106, -0.88647412, -0.7313306 ],
       [ 0.47819983, -1.03307414,  0.99312872]])

In [7]:
np.dot(arr.T, arr)

array([[ 6.4233868 , -0.67184059,  2.390207  ],
       [-0.67184059,  5.51821135, -3.07440119],
       [ 2.390207  , -3.07440119,  7.78683639]])

In [16]:
arr = np.arange(16).reshape((2, 2, 4))

In [17]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [18]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [19]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [20]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])