In [2]:
import numpy as np

In [5]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='<U4')

In [4]:
data = np.random.randn(7, 4)

data

array([[ 2.09818445,  0.50252227, -0.26766655,  0.75458721],
       [ 0.93019829, -0.36084371,  0.75773089, -0.29738691],
       [-0.50778126, -0.6877544 ,  0.1670542 ,  0.768122  ],
       [-1.50336081, -0.33055109, -1.37419982,  1.69384937],
       [ 0.98021138,  0.6028569 , -0.52576364, -1.49035992],
       [ 0.19319928, -0.89104565,  1.72532582, -1.17645783],
       [-0.73440375, -0.45245692,  1.06299021, -0.58851909]])

In [6]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [7]:
data[names == 'Bob']

array([[ 2.09818445,  0.50252227, -0.26766655,  0.75458721],
       [-1.50336081, -0.33055109, -1.37419982,  1.69384937]])

In [8]:
data[names == 'Bob', 2:]

array([[-0.26766655,  0.75458721],
       [-1.37419982,  1.69384937]])

In [9]:
data[names == 'Bob', 3]

array([ 0.75458721,  1.69384937])

In [10]:
names !='Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [11]:
data[~(names == 'Bob')]

array([[ 0.93019829, -0.36084371,  0.75773089, -0.29738691],
       [-0.50778126, -0.6877544 ,  0.1670542 ,  0.768122  ],
       [ 0.98021138,  0.6028569 , -0.52576364, -1.49035992],
       [ 0.19319928, -0.89104565,  1.72532582, -1.17645783],
       [-0.73440375, -0.45245692,  1.06299021, -0.58851909]])

In [12]:
cond = names == 'Bob'
data[~cond]

array([[ 0.93019829, -0.36084371,  0.75773089, -0.29738691],
       [-0.50778126, -0.6877544 ,  0.1670542 ,  0.768122  ],
       [ 0.98021138,  0.6028569 , -0.52576364, -1.49035992],
       [ 0.19319928, -0.89104565,  1.72532582, -1.17645783],
       [-0.73440375, -0.45245692,  1.06299021, -0.58851909]])

In [13]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [14]:
data[mask]

array([[ 2.09818445,  0.50252227, -0.26766655,  0.75458721],
       [-0.50778126, -0.6877544 ,  0.1670542 ,  0.768122  ],
       [-1.50336081, -0.33055109, -1.37419982,  1.69384937],
       [ 0.98021138,  0.6028569 , -0.52576364, -1.49035992]])

In [15]:
data[data < 0] = 0

In [16]:
data

array([[ 2.09818445,  0.50252227,  0.        ,  0.75458721],
       [ 0.93019829,  0.        ,  0.75773089,  0.        ],
       [ 0.        ,  0.        ,  0.1670542 ,  0.768122  ],
       [ 0.        ,  0.        ,  0.        ,  1.69384937],
       [ 0.98021138,  0.6028569 ,  0.        ,  0.        ],
       [ 0.19319928,  0.        ,  1.72532582,  0.        ],
       [ 0.        ,  0.        ,  1.06299021,  0.        ]])

In [17]:
data[names != 'Joe'] = 7

In [18]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.93019829,  0.        ,  0.75773089,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.19319928,  0.        ,  1.72532582,  0.        ],
       [ 0.        ,  0.        ,  1.06299021,  0.        ]])